site_name: "Contact Store"
site_description: 'A modern contacts Android API.'
site_author: "Alex Styl"
repo_url: https://github.com/alexstyl/contactstore
repo_name: alexstyl/contactstore
site_url: 'https://alexstyl.github.io/contactstore/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: indigo
    accent: light blue
  font:
      text: 'Roboto'
      code: 'JetBrains Mono'

  features:
      - content.code.annotate

nav:
  - 'Introduction': index.md
  - 'Reading contacts' : fetching_contacts.md
  - 'Writing contacts' : modify_contacts.md
  - 'How-tos':
      - '🖼 Contact photos': contact_photos.md
      - '🏎 Best practices': best_practices.md
  - 'Contributing' : contributing.md
  - 'Testing (experimental)': testing.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - codehilite:
      guess_lang: false
